// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prices.Data;

#nullable disable

namespace Prices.Migrations
{
    [DbContext(typeof(PriceDbContext))]
    partial class PriceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prices.Data.Models.StockEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Apple Inc.",
                            Ticker = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Alphabet Inc.",
                            Ticker = "GOOGL"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "NVIDIA Corporation",
                            Ticker = "NVDA"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Microsoft Corporation",
                            Ticker = "MSFT"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Amazon.com Inc.",
                            Ticker = "AMZN"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Meta Platforms Inc.",
                            Ticker = "FB"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
